---
    apiVersion: tekton.dev/v1beta1
    kind: Task
    metadata:
      name: zcash-build-bench-mem
    spec:    
      params:
        - name: JOBS
          default: "4"
          type: string
        - name: BUILD_FOR_HOST
          default: x86_64-pc-linux-gnu
          type: string
        - name: CONFIGURE_FLAGS
          default: ""
          type: string
        - name: BUILD_CONTAINER
          default: electriccoinco/zcashd-bench-debian10
          type: string
        - name: TEST_TARGET
          default: ""
          type: string
      resources:
        inputs:
          - name: source
            type: git
      steps:
        - name: build
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cd workspace/source
            echo $(git rev-parse HEAD)
            echo $(git rev-parse --short HEAD)
            
            if [ "$(params.BUILD_FOR_HOST)" == "x86_64-apple-darwin18" ]
            then
                mkdir -p depends/SDKs
                curl -fs https://ecc.mypinata.cloud/ipfs/QmeSwckvSCGL9SXGdEHoAyqXdzD7T9HYTwsC34Bj5EVDF5 \
                  -o depends/SDKs/Xcode-11.3.1-11C505-extracted-SDK-with-libcxx-headers.tar.gz
                tar zxvf depends/SDKs/Xcode-11.3.1-11C505-extracted-SDK-with-libcxx-headers.tar.gz \
                  -C depends/SDKs
            fi              
    
            CONFIGURE_FLAGS=$(params.CONFIGURE_FLAGS) HOST=$(params.BUILD_FOR_HOST) ./zcutil/build.sh -j$(params.JOBS)
    
        - name: bench-sleep
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory sleep | python ./mem_metrics.py
    
        - name: bench-createsaplingspend
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory createsaplingspend | python ./mem_metrics.py
    
        - name: bench-verifysaplingspend
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory verifysaplingspend | python ./mem_metrics.py
    
        - name: bench-createsaplingoutput
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory createsaplingoutput | python ./mem_metrics.py
    
        - name: bench-verifysaplingoutput
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory verifysaplingoutput | python ./mem_metrics.py
    
        - name: bench-createjoinsplit
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory createjoinsplit | python ./mem_metrics.py
    
        - name: bench-verifyjoinsplit
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory verifyjoinsplit | python ./mem_metrics.py
    
        - name: bench-verifyequihash
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory verifyequihash | python ./mem_metrics.py
    
        - name: bench-loadwallet-200k-recv
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory loadwallet 200k-recv | python ./mem_metrics.py
    
        - name: bench-loadwallet-200k-send
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory loadwallet 200k-send | python ./mem_metrics.py
    
        - name: bench-listunspent-200k-recv
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory listunspent 200k-recv | python ./mem_metrics.py
    
        - name: bench-listunspent-200k-send
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp -r /home/benchmark-200k-UTXOs.tar.xz /workspace/source
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory listunspent 200k-send | python ./mem_metrics.py
    
        - name: bench-connectblocksapling
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp -r /home/block-1723244.tar.xz /workspace/source
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory connectblocksapling | python ./mem_metrics.py
    
        - name: bench-connectblockorchard
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp -r /home/block-1708048.tar.xz /workspace/source
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory connectblockorchard | python ./mem_metrics.py
    
        - name: bench-connectblockslow
          image: $(params.BUILD_CONTAINER)
          script: |
            #!/bin/bash
            set -o pipefail
            cp -a /home/.zcash-params $HOME/
            cp -r /home/block-107134.tar.xz /workspace/source
            cp /home/mem_metrics.py /workspace/source
            cd /workspace/source
    
            ./qa/zcash/performance-measurements.sh memory connectblockslow | python ./mem_metrics.py
